### ISSUE TITLE
Restore packages when project.json changes

### ISSUE THREAD

**Issue by davidfowl** [aspnet/dnx-watch#9] opened 2015-09-28 07:22 UTC
Should we make the watcher do more than just watch? Maybe it could also restore packages when things change (using similar logic to what VS has today). This would play well with the launching of DTH.

**Comment by muratg** [comment] 2015-10-02 17:58
Neat idea.  How about running the scripts when those change?

**Comment by victorhurdugaci** [comment] 2015-12-03 22:18
Duplicate of https://github.com/aspnet/dnx-watch/issues/8

Same resolution: the watcher shouldn't run restore by default

**Closed by victorhurdugaci** 2015-12-03 22:18 UTC
